#!/bin/bash

ln -sf /usr/share/zoneinfo/Asia/Manila  /etc/localtime
hwclock --systohc --utc
echo en_US.UTF-8 UTF-8 >> /etc/locale.gen
locale-gen
echo LANG=en_US.UTF-8 > /etc/locale.conf

echo ScrubbyHost > /etc/hostname

mkinitcpio -p linux-lts
useradd -m -G sys,wheel,users,adm,log -s /bin/bash scrubs

passwd

echo "
    127.0.0.1 localhost
    ::        localhost
    127.0.1.1  ScrubbyHost.localdomain ScrubbyHost" > /etc/hosts

sed -i 's/# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/g' /etc/sudoers
echo "scrubs ALL=(ALL) ALL" >> /etc/sudoers

sed -i "s/#\[multilib]/[multilib]/" /etc/pacman.conf
sed -i "$!N;s/\(\[multilib]\n\)#\(Include\)/\1\2/;P;D" /etc/pacman.conf

pacman -Syy

pacman -S grub efibootmgr os-prober
grub-install --target=x86_64-efi --bootloader-id=grub --efi-directory=/boot/efi
grub-mkconfig -o /boot/grub/grub.cfg

