#!/bin/bash

set -e

[[ -f "constants.conf" ]] && source ./constants.conf || exit 0

TIMEZONE="Asia/Manila"

ln -sf /usr/share/zoneinfo/${TIMEZONE} /etc/localtime

hwclock --systohc
locale-gen

echo "LANG=en_US.UTF-8" > /etc/locale.conf

# /etc/vconsole.conf

echo "ScrubbyHost" > /etc/hostname

USERNAME="scrubs"
PASSWORD="1234"

echo "root:${PASSWORD}" | chpasswd
useradd -m $USERNAME
echo "$USERNAME:${PASSWORD}" | chpasswd

whereis sudo
usermod -aG wheel,audio,video,optical,storage $USERNAME
groups $USERNAME

sed -i 's/# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/g' /etc/sudoers
echo "$USERNAME ALL=(ALL) ALL" >> /etc/sudoers

pacman -Sy grub

[[ "$BOOT_TYPE" == "UEFI" ]] && pacman -Sy efibootmgr

[[ "$BOOT_TYPE" == "UEFI" && "$SYSTEM_BIT_OS" == "64" ]] && grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB
[[ "$BOOT_TYPE" == "LEGACY" ]] && grub-install --target=i386-pc $TARGET_DISK

grub-mkconfig -o /boot/grub/grub.cfg