#!/bin/bash

set -e

if [[ -f "constants.conf" ]] && rm -rvf ./constants.conf

TARGET_DISK="/dev/sda"

[[ $(cat /sys/firmware/efi/fw_platform_size) == "64" ]] && SYSTEM_BIT_OS="64"
[[ $(cat /sys/firmware/efi/fw_platform_size) == "32" ]] && SYSTEM_BIT_OS="32"

[[ ! $(ip link) && $(ping archlinux.org) ]] && exit 0

[[ -d "/sys/firmware/efi" ]] && BOOT_TYPE="UEFI" || BOOT_TYPE="LEGACY"

[[ "$BOOT_TYPE" == "UEFI" ]] && BOOT_DISK_SIZE="+300M"
[[ "$BOOT_TYPE" == "LEGACY" ]] && BOOT_DISK_SIZE="+1M"

loadkeys en
setfont ter-132b
timedatectl

umount -A --recursive /mnt && echo "umount" || echo "cant umount no mounted found"
swapoff -a
wipefs --all --force $TARGET_DISK
sgdisk -Z $TARGET_DISK
sgdisk -a 2048 -o $TARGET_DISK

if [[ "$BOOT_TYPE" == "UEFI" ]]; then
    sgdisk -n 1::$DISK_SIZE --typecode=1:ef00 --change-name=1:'BOOT' $TARGET_DISK
    sgdisk -n 2::-0 --typecode=2:8e00 --change-name=2:'ROOT' $TARGET_DISK
elif [[ "$BOOT_TYPE" == "LEGACY" ]]; then
    sgdisk -n 1::-0 --typecode=1:8e00 --change-name=1:'ROOT' $TARGET_DISK
fi

if [[ "$BOOT_TYPE" == "UEFI" ]]; then
    mkfs.fat -F 32 ${TARGET_DISK}1
    mkfs.ext4 ${TARGET_DISK}2
    mount --mkdir ${TARGET_DISK}1 /mnt/boot
    mount ${TARGET_DISK}2 /mnt
elif [[ "$BOOT_TYPE" == "LEGACY" ]]; then
    mkfs.ext4 ${TARGET_DISK}1
    mount ${TARGET_DISK}1 /mnt
fi

pacstrap -K /mnt base linux linux-firmware
genfstab -U /mnt >> /mnt/etc/fstab

echo " 
    BOOT_TYPE=$BOOT_TYPE\n
    SYSTEM_BIT_OS=$SYSTEM_BIT_OS\n
    TARGET_DISK=$TARGET_DISK" > constant.conf

cp ./constant.conf /mnt
cp ./chroot /mnt

arch-chroot /mnt ./chroot