#!/bin/bash

[ -d /sys/firmware/efi/efivars ] && BOOT_TYPE="UEFI" || BOOT_TYPE="LEGACY"

loadkeys en
setfont ter-132b
timedatectl

umount -a
swapoff -a
wipefs --all --force /dev/sda

fdisk -l
read -p "check is all cleared disk"

sgdisk -Z /dev/sda
sgdisk -a 2048 -o /dev/sda

sgdisk -n 1::+512M --typecode=1:ef00 --change-name=1:'BOOT' /dev/sda
sgdisk -n 2::-0 --typecode=2:8300 --change-name=2:'ROOT' /dev/sda

mkfs.fat -F32 /dev/sda1
mkfs.ext4 /dev/sda2

mount /dev/sda2 /mnt

# -- test -- #
mkdir -p /mnt/boot/efi
mount /dev/sda1 /mnt/boot/efi

ls -R /mnt/boot | grep ":$"
read -p "Check if /boot/efi created"

# -- default -- #
# pacstrap /mnt base base-devel linux linux-firmware linux-headers

# -- test -- #
pacstrap /mnt base base-devel linux linux-firmware linux-headers grub efibootmgr os-prober

genfstab -U /mnt >> /mnt/etc/fstab

cp ./chroot /mnt

arch-chroot /mnt /chroot