#!/bin/bash

pacman-key --init && pacman-key --populate

# [ -d /sys/firmware/efi/efivars ] && BOOT_TYPE="UEFI" || BOOT_TYPE="LEGACY"

# loadkeys en
setfont ter-132b
# timedatectl

umount -a
swapoff -a
wipefs --all --force /dev/sda
sgdisk -Z /dev/sda
sgdisk -a 2048 -o /dev/sda

sgdisk -n 1::+512M --typecode=1:ef00 --change-name=1:'BOOT' /dev/sda
sgdisk -n 2::-0 --typecode=2:8300 --change-name=2:'ROOT' /dev/sda

mkfs.fat -F32 /dev/sda1
mkfs.ext4 /dev/sda2

mount /dev/sda2 /mnt
mkdir -p /mnt/boot
mount /dev/sda1 /mnt/boot

pacstrap /mnt base linux linux-firmware

genfstab -U /mnt >> /mnt/etc/fstab

cp ./chroot /mnt

arch-chroot /mnt /chroot