#!/bin/bash

git clone https://aur.archlinux.org/skypeforlinux-stable-bin.git && ./skypeforlinux makepkg -si
git clone https://aur.archlinux.org/visual-studio-code-bin.git && ./visual-studio-code-bin makepkg -si
git clone https://aur.archlinux.org/brave-bin.git && ./brave-bin makepkg -si
git clone https://aur.archlinux.org/nohang.git && ./nohang makepkg -si
git clone https://aur.archlinux.org/gitkraken.git && ./gitkraken makepkg -si

pacman -S docker docker-compose
systemctl enable docker.service