#!/bin/bash

pacman-key --init && pacman-key --populate

# -- default -- #
# ln -sf /usr/share/zoneinfo/Asia/Manila  /etc/localtime

hwclock --systohc --utc
# -- default -- #
# sed -i 's/#en_US.UTF-8/en_US.UTF-8/g' /etc/locale.gen
locale-gen
# -- default -- #
# echo LANG=en_US.UTF-8 > /etc/locale.conf

# -- default -- #
# echo scrubs > /etc/hostname

mkinitcpio -p linux
useradd -m -G sys,wheel,users,adm,log -s /bin/bash scrubs

echo "root:1234" | chpasswd
echo "scrubs:1234" | chpasswd

# -- default -- #
# echo "
#     127.0.0.1 localhost
#     ::        localhost
#     127.0.1.1  scrubs.localdomain scrubs" > /etc/hosts

# sed -i 's/# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/g' /etc/sudoers
# echo "scrubs ALL=(ALL) ALL" >> /etc/sudoers

# sed -i "s/#\[multilib]/[multilib]/" /etc/pacman.conf
# sed -i "$!N;s/\(\[multilib]\n\)#\(Include\)/\1\2/;P;D" /etc/pacman.conf

# -- test -- #
systemctl enable NetworkManager
systemctl enable dhcpcd
systemctl enable iwd.service 
systemctl enable zram-swap.service

pacman -Syy

# grub-install --target=x86_64-efi --bootloader-id=GRUB --efi-directory=/boot/efi --removable
grub-install --target=x86_64-efi --bootloader-id=GRUB --efi-directory=/boot/efi
grub-mkconfig -o /boot/grub/grub.cfg
