#!/bin/bash

ENCRYPT_DRIVE=true

pacman-key --init && pacman-key --populate

ln -sf /usr/share/zoneinfo/Asia/Manila  /etc/localtime
hwclock --systohc -w --localtime

sed -i 's/#en_US.UTF-8/en_US.UTF-8/g' /etc/locale.gen
locale-gen

echo "LANG=en_US.UTF-8" > /etc/locale.conf

echo scrubs > /etc/hostname

mkinitcpio -p linux
useradd -m -G sys,wheel,users,adm,log -s /bin/bash scrubs

echo "root:1234" | chpasswd
echo "scrubs:1234" | chpasswd

echo "
    127.0.0.1 localhost
    ::        localhost
    127.0.1.1  scrubs.localdomain scrubs" > /etc/hosts

sed -i 's/# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/g' /etc/sudoers
echo "scrubs ALL=(ALL) ALL" >> /etc/sudoers

sed -i "s/#\[multilib]/[multilib]/" /etc/pacman.conf
sed -i "$!N;s/\(\[multilib]\n\)#\(Include\)/\1\2/;P;D" /etc/pacman.conf

systemctl enable NetworkManager
systemctl enable dhcpcd
systemctl enable iwd.service 
systemctl enable zram-swap.service

pacman -Syy

# grub-install --target=x86_64-efi --bootloader-id=GRUB --efi-directory=/boot/efi --removable
grub-install --target=x86_64-efi --bootloader-id=GRUB --efi-directory=/boot/efi

[[ "$ENCRYPT_DRIVE" == true ]]; then
STORAGE_NAME="shingha"
VOLGRP="scrubs"
new_disk="/dev/sda2"
disk_id=$(blkid | grep "${new_disk}" | cut -d' ' -f2 | cut -d'=' -f2 | sed -e 's/"//g')
tag="GRUB_CMDLINE_LINUX=\"\""
value="GRUB_CMDLINE_LINUX=\"cryptdevice=UUID=$disk_id:$STORAGE_NAME root=\/dev\/mapper\/$VOLGRP-ROOT\""
sed -i "s/$tag/$value/g" /etc/default/grub
fi

grub-mkconfig -o /boot/grub/grub.cfg
