#!/bin/bash

[ -d /sys/firmware/efi/efivars ] && BOOT_TYPE="UEFI" || BOOT_TYPE="LEGACY"

loadkeys en
# setfont ter-132b
timedatectl

umount -A --recursive /mnt
swapoff -a
wipefs --all --force /dev/sda

sgdisk -Z /dev/sda
sgdisk -a 2048 -o /dev/sda

sgdisk -n 1::+512M --typecode=1:ef00 --change-name=1:'BOOT' /dev/sda
# sgdisk -n 2::-0 --typecode=2:8300 --change-name=2:'ROOT' /dev/sda -- pc bonbon desktop
sgdisk -n 2::-0 --typecode=2:8304 --change-name=2:'ROOT' /dev/sda

mkfs.fat -F32 /dev/sda1
mkfs.ext4 /dev/sda2

mount /dev/sda2 /mnt

mkdir -p /mnt/boot/efi
mount /dev/sda1 /mnt/boot/efi

pacstrap /mnt --noconfirm --needed base base-devel linux linux-firmware linux-headers grub efibootmgr os-prober

# -- test -- #
pacstrap -i /mnt --noconfirm --needed NetworkManager dhcpcd iwd

echo scrubs > /mnt/etc/hostname

ls /mnt/etc | grep "host"
cat /mnt/etc/host

ln -sf /mnt/usr/share/zoneinfo/Asia/Manila  /mnt/etc/localtime

echo "
    127.0.0.1 localhost
    ::        localhost
    127.0.1.1  scrubs.localdomain scrubs" > /mnt/etc/hosts

ls /mnt/etc | grep "hosts"
cat /mnt/etc/hosts

sed -i 's/# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/g' /mnt/etc/sudoers

echo "scrubs ALL=(ALL) ALL" >> /mnt/etc/sudoers

ls /mnt/etc | grep "sudoers"
cat /mnt/etc/sudoers


sed -i "s/#\[multilib]/[multilib]/" /mnt/etc/pacman.conf
sed -i "$!N;s/\(\[multilib]\n\)#\(Include\)/\1\2/;P;D" /mnt/etc/pacman.conf

ls /mnt/etc | grep "pacman.conf"
cat /mnt/etc/pacman.conf

swap_size="2g"

echo "
[Unit]
Description=zRam block devices swapping

[Service]
Type=oneshot
ExecStart=/usr/bin/bash -c 'modprobe zram && echo lz4 > /sys/block/zram0/comp_algorithm && echo ${swap_size} > /sys/block/zram0/disksize && mkswap --label zram0 /dev/zram0 && swapon --priority 100 /dev/zram0'
ExecStop=/usr/bin/bash -c 'swapoff /dev/zram0 && rmmod zram'
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target

" > /mnt/etc/systemd/system/zram-swap.service

ls /mnt/etc/systemd/system | grep "zram-swap.service"
cat /mnt/etc/systemd/system/zram-swap.service

genfstab -U /mnt >> /mnt/etc/fstab

cp ./chroot /mnt

arch-chroot /mnt /chroot