#!/bin/sh

# echo "" > logfile.txt

# exec 3>&1 4>&2
# trap 'exec 2>&4 1>&3' 0 1 2 3
# exec 1>logfile.txt 2>&1

export MAIN_PATH=$PWD

source $MAIN_PATH/bin/bin.sh
source $MAIN_PATH/test/test.sh
source $MAIN_PATH/config/install_bash_packages.sh

[[ ! -d "$MAIN_PATH/bash_modules" ]] && install_bash_packages
load_bash_package

loadkeys us # -- not created bin file

input_arguments $@ 

# Changing variable key exports prepend ARCH_${variable}
while [[ $# -gt 0 ]]; do
    key="$1"
    key=$(echo "ARCH_${key#--}" | tr 'a-z' 'A-Z')

    export "$key=$2"
    shift
    shift
done

local -a scripts=(
    system_variables 
    check_environment_variables 
    populate_keyring 
    set_date 
    partition 
    base_package 
    # -- core ---
    modify_files 
    core_packages 
    start_services 
    # -- error -- # 
    user_manage 
    grub_install
)

add_pause=false

local -i count=0

echo "" > logfile.txt

for script in ${scripts[@]}; do
    count=$(($count+1))

    $script

   [[ $add_pause == true ]] && read -p "** ${count} - ${script} **"
done

# -- my command --
# ./arch --username "user" --password "1234" --hostname mynetdotnet --kernel hardened --settings 0 --target_disk /dev/sda --is_encrypt true --timezone Asia/Manila