#!/bin/bash

declare +i -r MAIN_DIRECTORY="${PWD}"

read -sp "password" $PASSWORD
echo "${PASSWORD}" | su root

echo "
#!/bin/bash

git clone https://aur.archlinux.org/$1 $HOME/Downloads/$1
" > /usr/local/bin/aur

echo "
#!/bin/bash

echo -e "\n$1" >> ~/Desktop/notes.txt
" > /usr/local/bin/note

# ---------------------------- git ------------------------- #

read -p "user" $USERNAME
read -p "email" $EMAIL

git config --global user.name "${USERNAME}"
git config --global user.email "${EMAIL}"

# ------------------------ polybar ------------------------------ #

sudo pacman -S polybar
if [[ ! -d "~/.config/polybar" ]]; then
mkdir ~/.config/polybar
cp ./files/polybar/config  ~/.config/polybar/config
cp ./files/polybar/launch  ~/.config/polybar/launch
chmod u+x ~/.config/polybar/launch
fi

# ------------------------ i3 ---------------------------------- #

cp ./files/i3/config  ~/.config/i3/config

# ------------------------ ranger ----------------------------- #

cp ./files/ranger/rc.conf ~/.config/ranger/rc.conf

# ------------------------- packages --------------------------- #

pacman_packages=(
    'docker'
    'docker-compose'
    'gimp'
)

pacman -Sy $pacman_packages

systemctl enable docker.service

# ------------------------- aur -------------------------- #

aur_packages=(
    'visual-studio-code-bin'
    'gitkraken'
    'beekeeper-studio'
    'simple-mtpfs'
    'wps-office'
)

for aur_package in aur_packages; do
$(aur $aur_package && cd $aur_package && makepkg -si)
done

# ------------------------- font ------------------------ #

wget -P ${PWD}/cascadia-code/CascadiaCode.zip https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/CascadiaCode.zip
mv cascadia-code /usr/local/share/fonts/cascadia-code
fc-cache -Ev


# ------------------------- dock ------------------------- #

if [[ ! -d "~/Desktop/PROJECT" ]] && mkdir ~/Desktop/PROJECT

echo '
#!/bin/bash

set +e

MAIN_PATH=$HOME/Desktop/PROJECT

cd $MAIN_PATH/laradock-ni-shingha

ENV_NAME="hive"
APPENDS="php-worker redis-webui"

[[ $1 == "up" ]] && sudo docker-compose --env-file $ENV_NAME.env up -d mysql php-fpm phpmyadmin nginx redis $APPENDS
[[ $1 == "down" ]] && sudo docker-compose --env-file $ENV_NAME.env down
if [[ $1 == "build" ]]; then
 read -p "What build? => $" build
 sudo docker-compose --env-file $ENV_NAME.env build "$build"
fi

PARAM="${2}"
[[ $1 == "exec" ]] && sudo docker-compose --env-file $ENV_NAME.env exec $2 bash
[[ $1 == "append" ]] &&  sed -i -r "s/^(APPENDS=\")([a-z| |-]+)\"/\1${PARAM}\"/g" $MAIN_PATH/dock
[[ $1 == "set-env" ]] &&  sed -i -r "s/^(ENV_NAME=\")([a-z| ]+)\"/\1${PARAM}\"/g" $MAIN_PATH/dock

' > ~/Desktop/PROJECT/dock

chmod u+x ~/Desktop/PROJECT/dock