#!/bin/bash

[[ ! -f "../../variable.conf" ]] && echo "Error 1" ; exit 1 || source ../../variable.conf && echo "source success variable.conf"

[ -d /sys/firmware/efi/efivars ] && BOOT_TYPE="UEFI" || BOOT_TYPE="LEGACY"

loadkeys en
# setfont ter-132b
timedatectl

[[ "$ENCRYPT_DRIVE" == true ]] && ./partition_drive/encrypt || ./partition_drive/normal

pacstrap /mnt --noconfirm --needed base base-devel linux$KERNEL linux-firmware linux$KERNEL-headers grub efibootmgr os-prober
pacstrap -i /mnt --noconfirm --needed networkmanager dhcpcd iwd

[[ "$ENCRYPT_DRIVE" == true ]] && pacstrap -i /mnt --needed --noconfirm lvm2 || echo "exit"
[[ "$ENCRYPT_DRIVE" == true ]] && sed -r -i 's/(HOOKS=)\((.*?)\)/\1(base udev autodetect modconf block keyboard encrypt lvm2 filesystems fsck)/g' /mnt/etc/mkinitcpio.conf || echo "exit"

echo scrubs > /mnt/etc/hostname

ls /mnt/etc | grep "host"
cat /mnt/etc/host

ln -sf /mnt/usr/share/zoneinfo/Asia/Manila  /mnt/etc/localtime

echo "
    127.0.0.1 localhost
    ::        localhost
    127.0.1.1  scrubs.localdomain scrubs" > /mnt/etc/hosts

ls /mnt/etc/hosts
cat /mnt/etc/hosts

sed -i 's/# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/g' /mnt/etc/sudoers

echo "scrubs ALL=(ALL) ALL" >> /mnt/etc/sudoers

ls /mnt/etc | grep "sudoers"
cat /mnt/etc/sudoers

sed -i "s/#\[multilib]/[multilib]/" /mnt/etc/pacman.conf
sed -i "$!N;s/\(\[multilib]\n\)#\(Include\)/\1\2/;P;D" /mnt/etc/pacman.conf

ls /mnt/etc | grep "pacman.conf"
cat /mnt/etc/pacman.conf

swap_size="${SWAP_SIZE}"

echo "
[Unit]
Description=zRam block devices swapping

[Service]
Type=oneshot
ExecStart=/usr/bin/bash -c 'modprobe zram && echo lz4 > /sys/block/zram0/comp_algorithm && echo ${swap_size} > /sys/block/zram0/disksize && mkswap --label zram0 /dev/zram0 && swapon --priority 100 /dev/zram0'
ExecStop=/usr/bin/bash -c 'swapoff /dev/zram0 && rmmod zram'
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target

" > /mnt/etc/systemd/system/zram-swap.service

ls /mnt/etc/systemd/system | grep "zram-swap.service"
cat /mnt/etc/systemd/system/zram-swap.service

genfstab -U /mnt >> /mnt/etc/fstab

cp ../../variable.conf /mnt
cp ./chroot /mnt

arch-chroot /mnt /chroot